title: Goktug GUMUS
description: Software Engineer | Firmware and Embedded Systems Development | System Design and Simulations
logo: assets/img/headshoot_img.png
# show_downloads: true
theme: jekyll-theme-minimal
